[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
version = "4.5.3"
name = "source-s3"
description = "Source implementation for S3."
authors = [ "Airbyte <contact@airbyte.io>",]
license = "MIT"
readme = "README.md"
documentation = "https://docs.airbyte.com/integrations/sources/s3"
homepage = "https://airbyte.com"
repository = "https://github.com/airbytehq/airbyte"
[[tool.poetry.packages]]
include = "source_s3"

[tool.poetry.dependencies]
python = "^3.9,<3.12"
wcmatch = "==8.4"
python-snappy = "==0.6.1"
dill = "==0.3.4"
pytz = "==2024.1"

[tool.poetry.scripts]
source-s3 = "source_s3.run:run"

[tool.poetry.dependencies.airbyte-cdk]
extras = [ "file-based",]
version = "==0.61.0"

[tool.poetry.dependencies.smart-open]
extras = [ "s3",]
version = "==5.1.0"

[tool.poetry.group.dev.dependencies]
pandas = "==2.0.3"
requests-mock = "^1.9.3"
pytest = "^6.1"
pytest-mock = "^3.6.1"
docker = "^7.0.0"
moto = "==4.2.14"
